# Generated by Django 4.1.4 on 2023-01-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('duracion', models.IntegerField()),
                ('fecha_de_lanzamiento', models.CharField(max_length=10)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
