# Generated by Django 4.1.4 on 2023-01-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='fecha_de_lanzamiento',
        ),
        migrations.AddField(
            model_name='peliculas',
            name='año_de_lanzamiento',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='duracion',
            field=models.CharField(max_length=50),
        ),
    ]
